# Generated by Django 3.0.7 on 2020-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='sample_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
