# Generated by Django 3.0.7 on 2020-07-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmsapp', '0002_sampledata_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
